# Generated by Django 4.2.15 on 2026-09-02 06:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('assessment_type', models.CharField(choices=[('assignment', 'تکلیف'), ('quiz', 'آزمون کوتاه'), ('exam', 'امتحان'), ('project', 'پروژه'), ('participation', 'مشارکت')], max_length=20, verbose_name='نوع')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='حداکثر نمره')),
                ('weight', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='وزن (درصد)')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course')),
            ],
            options={
                'verbose_name': 'ارزیابی',
                'verbose_name_plural': 'ارزیابی\u200cها',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نمره')),
                ('feedback', models.TextField(blank=True, verbose_name='بازخورد')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نمره')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.assessment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assessments', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'نمره',
                'verbose_name_plural': 'نمرات',
                'unique_together': {('assessment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='نمره نهایی')),
                ('letter_grade', models.CharField(blank=True, choices=[('A+', 'عالی+'), ('A', 'عالی'), ('B+', 'خوب+'), ('B', 'خوب'), ('C+', 'متوسط+'), ('C', 'متوسط'), ('D', 'قابل قبول'), ('F', 'مردود')], max_length=5, verbose_name='نمره حروفی')),
                ('passed', models.BooleanField(default=False, verbose_name='قبول شده')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ محاسبه')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='courses.course')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_grade', to='enrollments.enrollment', verbose_name='ثبت\u200cنام')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'نمره نهایی',
                'verbose_name_plural': 'نمرات نهایی',
                'unique_together': {('course', 'student')},
            },
        ),
    ]
