# Generated by Django 4.2.15 on 2026-09-03 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgrade',
            name='student',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='graded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assessments', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو'),
        ),
    ]
