# Generated by Django 4.2.15 on 2026-09-02 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان جلسه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('session_number', models.PositiveIntegerField(verbose_name='شماره جلسه')),
                ('date', models.DateField(verbose_name='تاریخ برگزاری')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='اتاق')),
                ('materials', models.TextField(blank=True, verbose_name='مواد آموزشی / تکالیف')),
                ('is_completed', models.BooleanField(default=False, verbose_name='برگزار شده')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
            ],
            options={
                'verbose_name': 'جلسه کلاس',
                'verbose_name_plural': 'جلسات کلاس',
                'ordering': ['date', 'start_time'],
                'unique_together': {('course', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب'), ('late', 'تاخیر'), ('excused', 'مرخصی')], default='present', max_length=10, verbose_name='وضعیت')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب\u200cها',
                'ordering': ['-session__date'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
