# Generated by Django 4.2.15 on 2026-09-02 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی کارگاه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای کارگاه',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کارگاه')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیحات کوتاه')),
                ('duration_type', models.CharField(choices=[('short', 'کوتاه\u200cمدت'), ('long', 'بلندمدت'), ('one', 'تک جلسه\u200cای'), ('intensive', 'فشرده')], max_length=15, verbose_name='نوع مدت')),
                ('status', models.CharField(choices=[('upcoming', 'پیش رو'), ('ongoing', 'در حال برگزاری'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='upcoming', max_length=15, verbose_name='وضعیت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('sessions_count', models.PositiveIntegerField(default=1, verbose_name='تعداد جلسات')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='حداکثر شرکت\u200cکننده')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ثبت\u200cنام')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='workshops/thumbnails/', verbose_name='تصویر بندانگشتی')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='workshops/covers/', verbose_name='تصویر کاور')),
                ('prerequisites', models.TextField(blank=True, verbose_name='پیش\u200cنیازها')),
                ('materials', models.TextField(blank=True, verbose_name='وسایل مورد نیاز')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل برگزاری')),
                ('is_online', models.BooleanField(default=False, verbose_name='آنلاین')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='workshops.workshopcategory', verbose_name='دسته\u200cبندی')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='instructors.instructor', verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'کارگاه',
                'verbose_name_plural': 'کارگاه\u200cها',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to=settings.AUTH_USER_MODEL, verbose_name='شرکت\u200cکننده')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام کارگاه',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای کارگاه',
                'unique_together': {('workshop', 'user')},
            },
        ),
    ]
