# Generated by Django 4.2.15 on 2026-09-03 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistration',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to=settings.AUTH_USER_MODEL, verbose_name='شرکت\u200cکننده'),
        ),
    ]
