# Generated by Django 4.2.15 on 2026-09-02 06:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150, verbose_name='نام نمایشی')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='اسلاگ')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
                ('specializations', models.JSONField(blank=True, default=list, verbose_name='تخصص\u200cها')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/photos/', verbose_name='عکس پروفایل')),
                ('resume', models.FileField(blank=True, null=True, upload_to='instructors/resumes/', verbose_name='رزومه')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت شخصی')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='اینستاگرام')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='تلگرام')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='سال\u200cهای تجربه')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانشجو')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='استاد ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
                'ordering': ['-is_featured', '-rating', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='InstructorPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='instructors/portfolio/', verbose_name='تصویر اثر')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال خلق')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='instructors.instructor')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
                'ordering': ['order'],
            },
        ),
    ]
