# Generated by Django 4.2.30 on 2026-08-22 21:40

import apps.common.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.file_uploads.vendor_logo_upload_to, verbose_name='لوگو'),
        ),
    ]
