# Generated by Django 4.2.30 on 2026-08-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero-slides/', verbose_name='تصویر')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='لیبل بالای عنوان')),
                ('title', models.CharField(max_length=200, verbose_name='متن بزرگ (تیتر)')),
                ('description', models.TextField(blank=True, verbose_name='متن کوچک (توضیح)')),
                ('primary_button_text', models.CharField(blank=True, max_length=50, verbose_name='متن دکمه اول')),
                ('primary_button_link', models.CharField(blank=True, help_text='مسیر داخلی مثل /products یا آدرس کامل خارجی مثل https://...', max_length=255, verbose_name='لینک دکمه اول')),
                ('secondary_button_text', models.CharField(blank=True, max_length=50, verbose_name='متن دکمه دوم')),
                ('secondary_button_link', models.CharField(blank=True, max_length=255, verbose_name='لینک دکمه دوم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / نمایش در سایت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'اسلاید هیرو',
                'verbose_name_plural': 'اسلایدهای هیرو',
                'ordering': ['order', 'id'],
            },
        ),
    ]
