# Generated by Django 4.2.30 on 2026-08-22 21:40

import apps.common.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to=apps.common.file_uploads.hero_slide_image_upload_to, verbose_name='تصویر'),
        ),
    ]
