# Generated by Django 4.2.15 on 2026-09-02 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام طرح')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت ماهانه (تومان)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='ویژگی\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'طرح اشتراک',
                'verbose_name_plural': 'طرح\u200cهای اشتراک',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('active', 'فعال'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('suspended', 'معلق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_type', models.CharField(choices=[('single', 'تک دوره'), ('subscription', 'اشتراک ماهانه')], default='single', max_length=20, verbose_name='نوع پرداخت')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('subscription_expires', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای اشتراک')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
