# Generated by Django 4.2.15 on 2026-09-02 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قالب')),
                ('background_image', models.ImageField(upload_to='certificates/templates/', verbose_name='تصویر پس\u200cزمینه')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificates/logos/', verbose_name='لوگو')),
                ('title_template', models.CharField(default='گواهینامه پایان دوره', help_text='از {student_name} و {course_name} می\u200cتوانید استفاده کنید', max_length=200, verbose_name='عنوان قالب')),
                ('description_template', models.TextField(blank=True, default='این گواهینامه به شرح زیر صادر می\u200cگردد:', verbose_name='متن قالب')),
                ('signature_left', models.ImageField(blank=True, null=True, upload_to='certificates/signatures/', verbose_name='امضای چپ')),
                ('signature_right', models.ImageField(blank=True, null=True, upload_to='certificates/signatures/', verbose_name='امضای راست')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('course', models.ForeignKey(blank=True, help_text='اگر خالی باشد، قالب عمومی است', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='courses.course', verbose_name='دوره مرتبط')),
            ],
            options={
                'verbose_name': 'قالب گواهینامه',
                'verbose_name_plural': 'قالب\u200cهای گواهینامه',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='شماره گواهینامه')),
                ('unique_code', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='کد یکتا')),
                ('student_name', models.CharField(max_length=200, verbose_name='نام دانشجو')),
                ('course_name', models.CharField(max_length=200, verbose_name='نام دوره')),
                ('instructor_name', models.CharField(blank=True, max_length=200, verbose_name='نام استاد')),
                ('issued_date', models.DateField(verbose_name='تاریخ صدور')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام دوره')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='نمره نهایی')),
                ('grade', models.CharField(blank=True, max_length=5, verbose_name='نمره حروفی')),
                ('hours_completed', models.PositiveIntegerField(default=0, verbose_name='ساعات تکمیل شده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('issued', 'صادر شده'), ('revoked', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/', verbose_name='فایل PDF')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('revoke_reason', models.TextField(blank=True, verbose_name='دلیل لغو')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='دوره')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollments.enrollment', verbose_name='ثبت\u200cنام')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.certificatetemplate', verbose_name='قالب')),
            ],
            options={
                'verbose_name': 'گواهینامه',
                'verbose_name_plural': 'گواهینامه\u200cها',
                'ordering': ['-issued_at'],
            },
        ),
    ]
