# Generated by Django 4.2.30 on 2026-08-09 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده\u200cشده')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش\u200cهای ناموفق')),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'کد یک\u200cبارمصرف پیامکی',
                'verbose_name_plural': 'کدهای یک\u200cبارمصرف پیامکی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAuthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_enabled', models.BooleanField(default=False, verbose_name='ورود با گوگل فعال باشد')),
                ('google_client_id', models.CharField(blank=True, help_text='از Google Cloud Console (APIs & Services → Credentials) گرفته می\u200cشود. این مقدار عمومی است.', max_length=255, verbose_name='Google Client ID')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='ورود با تلگرام فعال باشد')),
                ('telegram_bot_username', models.CharField(blank=True, help_text='بدون @ ، مثلاً YashilArtBot - این مقدار عمومی است.', max_length=64, verbose_name='یوزرنیم ربات تلگرام')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='از @BotFather گرفته می\u200cشود - این مقدار محرمانه است و هرگز به فرانت\u200cاند ارسال نمی\u200cشود.', max_length=100, verbose_name='توکن ربات تلگرام')),
                ('sms_otp_enabled', models.BooleanField(default=False, verbose_name='ورود با کد پیامکی فعال باشد')),
                ('sms_provider', models.CharField(default='kavenegar', help_text='فعلاً فقط kavenegar پیاده\u200cسازی شده.', max_length=30, verbose_name='سرویس\u200cدهنده پیامک')),
                ('sms_api_key', models.CharField(blank=True, max_length=100, verbose_name='کلید API سرویس پیامک')),
                ('sms_sender_line', models.CharField(blank=True, max_length=20, verbose_name='شماره خط ارسال (اختیاری)')),
            ],
            options={
                'verbose_name': 'تنظیمات ورود اجتماعی',
                'verbose_name_plural': 'تنظیمات ورود اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='SocialIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'گوگل'), ('telegram', 'تلگرام'), ('phone', 'شماره موبایل')], max_length=20, verbose_name='سرویس')),
                ('provider_user_id', models.CharField(max_length=191, verbose_name='شناسه کاربر در سرویس')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اتصال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_identities', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'هویت اجتماعی',
                'verbose_name_plural': 'هویت\u200cهای اجتماعی',
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
