# Generated by Django 4.2.15 on 2026-09-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp_socialauthsettings_socialidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_instructor',
            field=models.BooleanField(default=False, help_text='آیا کاربر استاد است؟', verbose_name='استاد'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='آیا کاربر دانشجو است؟', verbose_name='دانشجو'),
        ),
    ]
