# Generated by Django 4.2.15 on 2026-09-02 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اثر')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات اثر')),
                ('medium', models.CharField(choices=[('painting', 'نقاشی'), ('sculpture', 'مجسمه\u200cسازی'), ('calligraphy', 'خوشنویسی'), ('digital', 'دیجیتال آرت'), ('photography', 'عکاسی'), ('pottery', 'سفالگری'), ('textile', 'نساجی و بافندگی'), ('mixed', 'تکنیک ترکیبی'), ('other', 'سایر')], max_length=20, verbose_name='تکنیک / مدیوم')),
                ('dimensions', models.CharField(blank=True, help_text='مثلاً 50x70 سانتی\u200cمتر', max_length=100, verbose_name='ابعاد')),
                ('year_created', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال خلق')),
                ('image', models.ImageField(upload_to='gallery/artworks/', verbose_name='تصویر اثر')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/', verbose_name='تصویر بندانگشتی')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('is_featured', models.BooleanField(default=False, verbose_name='اثر ویژه')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('is_for_sale', models.BooleanField(default=False, verbose_name='قابل فروش')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت فروش (تومان)')),
                ('is_sold', models.BooleanField(default=False, verbose_name='فروخته شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_artworks', to=settings.AUTH_USER_MODEL, verbose_name='هنرمند')),
            ],
            options={
                'verbose_name': 'اثر هنری',
                'verbose_name_plural': 'آثار هنری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی گالری',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای گالری',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نمایشگاه')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('cover_image', models.ImageField(upload_to='gallery/exhibitions/', verbose_name='تصویر کاور')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل نمایشگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='مجازی')),
            ],
            options={
                'verbose_name': 'نمایشگاه',
                'verbose_name_plural': 'نمایشگاه\u200cها',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.galleryartwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر گالری',
                'verbose_name_plural': 'نظرات گالری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='galleryartwork',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='gallery.gallerycategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='galleryartwork',
            name='exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='gallery.galleryexhibition', verbose_name='نمایشگاه'),
        ),
        migrations.AddField(
            model_name='galleryartwork',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='instructors.instructor', verbose_name='استاد راهنما'),
        ),
        migrations.CreateModel(
            name='GalleryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gallery.galleryartwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_likes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک\u200cها',
                'unique_together': {('artwork', 'user')},
            },
        ),
    ]
