# Generated by Django 4.2.30 on 2026-08-27 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderitem_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, help_text='شماره خودکار منحصربفرد فاکتور', max_length=30, unique=True, verbose_name='شماره فاکتور')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادر شده'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده'), ('archived', 'بایگانی شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('buyer_full_name', models.CharField(max_length=150, verbose_name='نام خریدار')),
                ('buyer_phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن خریدار')),
                ('buyer_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل خریدار')),
                ('buyer_address', models.TextField(blank=True, verbose_name='آدرس صورتحساب')),
                ('buyer_postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='جمع آیتم\u200cها (تومان)')),
                ('discount_total', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مجموع تخفیف (تومان)')),
                ('tax_total', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مجموع مالیات (تومان)')),
                ('grand_total', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مبلغ نهایی (تومان)')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای فاکتور')),
                ('is_archived', models.BooleanField(default=False, verbose_name='بایگانی شده')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بایگانی')),
                ('email_sent', models.BooleanField(default=False, verbose_name='ایمیل ارسال شده')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال ایمیل')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order', verbose_name='سفارش مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='خریدار')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-created_at'],
                'permissions': [('view_all_invoices', 'مشاهده همه فاکتورها'), ('archive_invoice', 'بایگانی فاکتور'), ('send_invoice_email', 'ارسال ایمیل فاکتور')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('variant_label', models.CharField(blank=True, max_length=100, verbose_name='مشخصات تنوع')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت واحد (تومان)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف ردیف (تومان)')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مالیات ردیف (تومان)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='فاکتور')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور',
            },
        ),
    ]
