# Generated by Django 4.2.30 on 2026-08-07 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_orderitem_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_transfer_enabled', models.BooleanField(default=True, verbose_name='کارت\u200cبه\u200cکارت فعال باشد')),
                ('card_number', models.CharField(blank=True, help_text='مثلاً 6037-9977-XXXX-XXXX', max_length=20, verbose_name='شماره کارت')),
                ('card_holder_name', models.CharField(blank=True, max_length=100, verbose_name='نام صاحب حساب')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('card_transfer_instructions', models.TextField(blank=True, help_text='مثلاً: لطفاً حتماً شماره سفارش را در توضیحات واریز بنویسید.', verbose_name='توضیحات اضافه برای مشتری')),
                ('online_gateway_enabled', models.BooleanField(default=False, verbose_name='درگاه آنلاین فعال باشد')),
                ('zarinpal_merchant_id', models.CharField(blank=True, help_text='از پنل زرین\u200cپال شما (merchant.zarinpal.com) گرفته می\u200cشود.', max_length=64, verbose_name='Merchant ID زرین\u200cپال')),
                ('zarinpal_sandbox', models.BooleanField(default=True, help_text='تا زمانی که Merchant ID واقعی و تاییدشده ندارید، این را روشن نگه دارید.', verbose_name='حالت آزمایشی (Sandbox)')),
            ],
            options={
                'verbose_name': 'تنظیمات پرداخت',
                'verbose_name_plural': 'تنظیمات پرداخت',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('card_transfer', 'کارت\u200cبه\u200cکارت'), ('zarinpal', 'درگاه آنلاین (زرین\u200cپال)')], max_length=20, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('submitted', 'در انتظار بررسی رسید'), ('verified', 'تاییدشده'), ('rejected', 'رد شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ (تومان)')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payment-receipts/', verbose_name='تصویر رسید')),
                ('gateway_authority', models.CharField(blank=True, max_length=64, verbose_name='کد Authority زرین\u200cپال')),
                ('gateway_ref_id', models.CharField(blank=True, max_length=64, verbose_name='کد پیگیری (RefID)')),
                ('admin_note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت ادمین')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='سفارش')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
