# Generated by Django 4.2.30 on 2026-08-22 21:40

import apps.common.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.file_uploads.category_image_upload_to, verbose_name='تصویر دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.file_uploads.product_image_upload_to, verbose_name='تصویر'),
        ),
    ]
